package runner

import (
	"context"
	"encoding/json"
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"reflect"
	"runtime/debug"
	"strconv"
	"time"

	"github.com/traefik/yaegi/interp"
	"github.com/traefik/yaegi/stdlib"
	"github.com/zr-hebo/script-agent/sdk"
)

// taskWrapper is Yaegi's precompiled interface bridge. W-method fields follow
// the alphabetical method order used by wrappers generated by yaegi extract.
type taskWrapper struct {
	IValue   any
	WPostRun func(context.Context, map[string]any, sdk.Outcome) error
	WPrepare func(context.Context, map[string]any) error
	WRun     func(context.Context, map[string]any) sdk.Outcome
}

func (w taskWrapper) Prepare(ctx context.Context, p map[string]any) error   { return w.WPrepare(ctx, p) }
func (w taskWrapper) Run(ctx context.Context, p map[string]any) sdk.Outcome { return w.WRun(ctx, p) }
func (w taskWrapper) PostRun(ctx context.Context, p map[string]any, o sdk.Outcome) error {
	return w.WPostRun(ctx, p, o)
}

func sdkSymbols() interp.Exports {
	return interp.Exports{"github.com/zr-hebo/script-agent/sdk/sdk": {
		"TaskRunner":      reflect.ValueOf((*sdk.TaskRunner)(nil)),
		"_TaskRunner":     reflect.ValueOf((*taskWrapper)(nil)),
		"BaseTask":        reflect.ValueOf((*sdk.BaseTask)(nil)),
		"Outcome":         reflect.ValueOf((*sdk.Outcome)(nil)),
		"Status":          reflect.ValueOf((*sdk.Status)(nil)),
		"StatusSucceeded": reflect.ValueOf(sdk.StatusSucceeded),
		"StatusFailed":    reflect.ValueOf(sdk.StatusFailed),
		"StatusTimedOut":  reflect.ValueOf(sdk.StatusTimedOut),
		"StatusCancelled": reflect.ValueOf(sdk.StatusCancelled),
	}}
}

type legacyTask struct {
	sdk.BaseTask
	handle func(context.Context, map[string]any) (map[string]any, error)
}

func (t legacyTask) Run(ctx context.Context, p map[string]any) sdk.Outcome {
	data, err := t.handle(ctx, p)
	status := sdk.StatusSucceeded
	if err != nil {
		status = sdk.StatusFailed
	}
	return sdk.Outcome{Status: status, Data: data, Error: err}
}

// GoEntry runs only in a disposable helper. The primary outcome is saved BEFORE
// PostRun, so a stuck/crashing cleanup hook cannot erase the Run result.
func GoEntry(ctx context.Context, sourcePath, paramsPath, resultPath, postPath string) (code int) {
	phaseFile := os.NewFile(3, "script-agent-events")
	if phaseFile != nil {
		defer phaseFile.Close()
	}
	notify := func(phase string) {
		if phaseFile != nil {
			_ = json.NewEncoder(phaseFile).Encode(map[string]string{"phase": phase})
		}
	}
	writeFailure := func(err error) {
		fmt.Fprintln(os.Stderr, err)
		_ = writeOutcome(resultPath, sdk.Outcome{Status: sdk.StatusFailed, Error: err})
		code = 1
	}
	defer func() {
		if p := recover(); p != nil {
			writeFailure(fmt.Errorf("load panic: %v", p))
			fmt.Fprintln(os.Stderr, string(debug.Stack()))
		}
	}()
	source, err := os.ReadFile(sourcePath)
	if err != nil {
		writeFailure(err)
		return
	}
	file, err := parser.ParseFile(token.NewFileSet(), sourcePath, source, parser.PackageClauseOnly)
	if err != nil || file.Name.Name != "usercode" {
		writeFailure(fmt.Errorf("Go source must declare package usercode: %v", err))
		return
	}
	data, err := os.ReadFile(paramsPath)
	if err != nil {
		writeFailure(err)
		return
	}
	var params map[string]any
	if err := json.Unmarshal(data, &params); err != nil {
		writeFailure(err)
		return
	}
	i := interp.New(interp.Options{Stdout: os.Stdout, Stderr: os.Stderr, Stdin: os.Stdin, Env: os.Environ()})
	if err := i.Use(stdlib.Symbols); err != nil {
		writeFailure(err)
		return
	}
	if err := i.Use(sdkSymbols()); err != nil {
		writeFailure(err)
		return
	}
	if _, err := i.EvalWithContext(ctx, string(source)); err != nil {
		writeFailure(err)
		return
	}
	var task sdk.TaskRunner
	legacy := false
	if factory, err := i.Eval("usercode.New"); err == nil {
		newTask, ok := factory.Interface().(func() sdk.TaskRunner)
		if !ok {
			writeFailure(fmt.Errorf("expected New() sdk.TaskRunner"))
			return
		}
		task = newTask()
		if task == nil {
			writeFailure(fmt.Errorf("New returned a nil TaskRunner"))
			return
		}
	} else {
		symbol, err := i.Eval("usercode.Handle")
		if err != nil {
			writeFailure(fmt.Errorf("expected New() sdk.TaskRunner (or legacy Handle): %w", err))
			return
		}
		handle, ok := symbol.Interface().(func(context.Context, map[string]any) (map[string]any, error))
		if !ok {
			writeFailure(fmt.Errorf("expected Handle(context.Context, map[string]any) (map[string]any, error)"))
			return
		}
		task, legacy = legacyTask{handle: handle}, true
	}
	var outcome sdk.Outcome
	prepareErr, prepareStack := safeError(func() error { return task.Prepare(ctx, params) })
	if prepareErr != nil {
		outcome = sdk.Outcome{Status: sdk.StatusFailed, Error: prepareErr, Stack: prepareStack}
	} else if ctx.Err() != nil {
		outcome = interrupted(ctx.Err()).Outcome
	} else {
		notify("run")
		outcome = safeRun(func() sdk.Outcome { return task.Run(ctx, params) })
	}
	if ctx.Err() != nil {
		outcome.Status, outcome.Error = interrupted(ctx.Err()).Status, ctx.Err()
		if reason, err := os.ReadFile(os.Getenv("SCRIPT_INTERRUPT_FILE")); err == nil && string(reason) == "timed_out" {
			outcome.Status, outcome.Error = sdk.StatusTimedOut, context.DeadlineExceeded
		}
	}
	if err := outcome.Validate(); err != nil {
		outcome = sdk.Outcome{Status: sdk.StatusFailed, Error: fmt.Errorf("invalid outcome: %w", err)}
	}
	if err := writeOutcome(resultPath, outcome); err != nil {
		outcome = sdk.Outcome{Status: sdk.StatusFailed, Error: fmt.Errorf("result_error: %w", err)}
		if err := writeOutcome(resultPath, outcome); err != nil {
			fmt.Fprintln(os.Stderr, err)
			return 1
		}
	}
	notify("post-run")
	if legacy {
		_ = writeOutcome(postPath, sdk.Outcome{Status: "skipped"})
		return 0
	}
	seconds, _ := strconv.Atoi(os.Getenv("SCRIPT_POST_RUN_TIMEOUT_SECONDS"))
	if seconds < 1 {
		seconds = 10
	}
	postCtx, cancel := context.WithTimeout(context.Background(), time.Duration(seconds)*time.Second)
	defer cancel()
	postErr, stack := safeError(func() error { return task.PostRun(postCtx, params, outcome) })
	post := sdk.Outcome{Status: sdk.StatusSucceeded, Error: postErr, Stack: stack}
	if postErr != nil {
		post.Status = sdk.StatusFailed
	}
	if postCtx.Err() != nil {
		post.Status, post.Error = sdk.StatusTimedOut, postCtx.Err()
	}
	if err := writeOutcome(postPath, post); err != nil {
		fmt.Fprintln(os.Stderr, err)
		return 1
	}
	return 0
}

func safeError(call func() error) (err error, stack string) {
	defer func() {
		if p := recover(); p != nil {
			err, stack = fmt.Errorf("panic: %v", p), string(debug.Stack())
		}
	}()
	err = call()
	return
}

func safeRun(call func() sdk.Outcome) (out sdk.Outcome) {
	err, stack := safeError(func() error { out = call(); return nil })
	if err != nil {
		out = sdk.Outcome{Status: sdk.StatusFailed, Error: err, Stack: stack}
	}
	return out
}

func writeOutcome(path string, outcome sdk.Outcome) (err error) {
	defer func() {
		if p := recover(); p != nil {
			err = fmt.Errorf("outcome serialization panic: %v", p)
		}
	}()
	data, err := json.Marshal(outcome)
	if err != nil {
		return err
	}
	if len(data) > MaxResultBytes {
		return fmt.Errorf("outcome exceeds %d bytes", MaxResultBytes)
	}
	return os.WriteFile(path, data, 0600)
}
